const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
function engine(){const e={window:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../assets/js/beijing-drive-core.js'),'utf8'),e);return e.window.BeijingDrive;}
function ticks(G,s,input,n){for(let i=0;i<n;i++)s=G.step(s,input,.025);return s;}
test('stationary steering turns front wheels without moving or rotating body',()=>{const G=engine(),a=G.initial(),b=ticks(G,a,{steer:1},40);assert.equal(b.x,a.x);assert.equal(b.y,a.y);assert.equal(b.heading,a.heading);assert.ok(b.wheel>.5);});
test('steering makes a moving vehicle follow an arc and changes heading',()=>{const G=engine(),a=G.initial(),b=ticks(G,a,{gas:true,steer:-1},40);assert.ok(b.heading<a.heading-.1);assert.ok(b.x<a.x);assert.ok(b.y<a.y);});
test('releasing steering centers wheels, not the car heading or road position',()=>{const G=engine();let s=ticks(G,G.initial(),{gas:true,steer:-1},20);const h=s.heading;s=ticks(G,s,{brake:true},40);assert.equal(s.wheel,0);assert.ok(Math.abs(s.heading-G.sample(s.d).angle)>.05);assert.ok(s.heading<h);});
test('driving straight does not automatically follow the first bend',()=>{const G=engine();const s=ticks(G,G.initial(),{gas:true},500);assert.ok(s.bumps>0);assert.ok(s.d<300);assert.equal(s.heading,-Math.PI/2);});
test('reverse changes travel direction and reverses steering yaw',()=>{const G=engine();let s=G.recover({...G.initial(),d:80});const h=s.heading,x=s.x,y=s.y;s=ticks(G,s,{gas:true,reverse:true,steer:1},30);assert.ok(s.speed<0);assert.ok(s.heading<h);assert.ok(s.y>y);assert.notEqual(s.x,x);});
test('parking needs aligned heading, bay position, release and dwell',()=>{const G=engine(),p=G.offset(G.length-34,25),s={...G.initial(),x:p.x,y:p.y,heading:p.angle,d:G.length-34,lane:25};assert.equal(ticks(G,s,{},90).done,true);assert.equal(ticks(G,{...s,heading:p.angle+.8},{},90).done,false);});
test('complete trip reachable using only throttle, brake and steering inputs',()=>{const G=engine();let s=G.initial();for(let i=0;i<60000&&!s.done;i++){const target=G.offset(Math.min(G.length-34,s.d+38),22),dx=target.x-s.x,dy=target.y-s.y,dist=Math.hypot(dx,dy),alpha=G.wrap(Math.atan2(dy,dx)-s.heading),wheel=Math.atan2(60*Math.sin(alpha),Math.max(8,dist));let speed=5;if(s.d>G.length-90)speed=2;if(s.d>G.length-37)speed=0;const light=G.signals.find(l=>l.at>s.d&&G.red(l,s.time)&&l.at-s.d<20);if(light)speed=0;s=G.step(s,{gas:s.speed<speed-.15,brake:s.speed>speed+.15,steer:Math.max(-1,Math.min(1,wheel/.55))},.025);}assert.ok(s.done,JSON.stringify(s));});
