const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
function engine(){const e={window:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../assets/js/beijing-drive-core.js'),'utf8'),e);return e.window.BeijingDrive;}
function ticks(G,s,input,n){for(let i=0;i<n;i++)s=G.step(s,input,.05);return s;}
test('accelerator, steering, coasting and brake control movement independently',()=>{const G=engine();let s=G.initial();s=ticks(G,s,{gas:true},30);assert.ok(s.d>20);assert.ok(s.speed>10);const lane=s.lane;s=ticks(G,s,{steer:-1},8);assert.ok(s.lane<lane);s=ticks(G,s,{brake:true},30);assert.equal(s.speed,0);const d=s.d;s=ticks(G,s,{},10);assert.equal(s.d,d);});
test('road shoulder limits speed; contact does not reset entire journey',()=>{const G=engine();let s={...G.initial(),d:700,lane:48,speed:15};s=G.step(s,{gas:true,steer:1},.05);assert.equal(s.lane,49);assert.equal(s.bumps,1);assert.ok(s.speed<=3);assert.ok(s.d>=700);});
test('red stop line records a crossing; stopping before the line is allowed',()=>{const G=engine();let s={...G.initial(),d:159,time:0,speed:10};s=G.step(s,{gas:true},.05);assert.equal(s.reds,1);s=ticks(G,{...G.initial(),d:140,speed:0},{brake:true},50);assert.equal(s.reds,0);assert.equal(s.d,140);});
test('exit requires right lane, but recovery remains possible without restarting',()=>{const G=engine();let s={...G.initial(),d:2879,lane:-22,speed:15};s=G.step(s,{gas:true},.05);assert.equal(s.d,2879);assert.equal(s.speed,0);s=ticks(G,s,{steer:1},50);assert.ok(s.lane>2);s=ticks(G,s,{gas:true},10);assert.ok(s.d>2880);});
test('parking requires right-hand bay, low speed, released accelerator and two seconds',()=>{const G=engine();let s={...G.initial(),d:G.length-20,lane:24};assert.equal(ticks(G,s,{gas:true,brake:true},50).done,false);assert.equal(ticks(G,{...s,lane:-22},{brake:true},50).done,false);assert.equal(ticks(G,s,{},30).done,false);assert.equal(ticks(G,s,{},45).done,true);});
test('complete trip can be driven through traffic, signals and exit then parked',()=>{const G=engine();let s=G.initial();for(let i=0;i<18000&&!s.done;i++){let target=G.zone(s).limit/3.6-2;const stop=G.signals.find(l=>l.at>s.d&&G.red(l,s.time));if(stop&&stop.at-s.d<s.speed*s.speed/24+20)target=0;if(s.d>G.length-90)target=3;if(s.d>G.length-35)target=0;let lane=22;const ahead=G.cars(s).find(c=>c.d>s.d&&c.d-s.d<110&&Math.abs(c.lane-s.lane)<20);if(ahead&&s.d<2700)lane=-ahead.lane;const input={gas:s.speed<target-.3,brake:s.speed>target+.3,steer:Math.abs(s.lane-lane)>2?Math.sign(lane-s.lane):0};s=G.step(s,input,.05);}assert.equal(s.done,true,JSON.stringify(s));assert.ok(s.d>G.length-65);});
test('all driving page assets exist; original route chapter remains separate',()=>{const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'drive-beijing.html'),'utf8');for(const m of html.matchAll(/(?:src|href)="([^"#]+)"/g))assert.ok(fs.existsSync(path.join(root,m[1].split('?')[0])),m[1]);assert.ok(fs.existsSync(path.join(root,'route.html')));});
