const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
function engine(){const env={window:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../assets/js/departure-core.js'),'utf8'),env);return env.window.Departure;}
function plan(D,s,list){for(const n of list){const r=D.append(s,n);assert.ok(r.state,r.error);s=r.state;}return s;}
function walk(D,s,list){s=plan(D,s,list);while(s.plan.length){const r=D.advance(s);assert.ok(r.state,r.error);s=r.state;}return s;}
test('planning requires contact, adjacency and does not move the vehicle',()=>{const D=engine();let s=D.initial();assert.ok(D.append(s,'west').error);s.contact=true;assert.ok(D.append(s,'drop').error);s=plan(D,s,['west','bridge','north','drop']);assert.equal(s.at,'home');assert.equal(s.minutes,0);assert.equal(D.preview(s).minutes,12);assert.ok(D.valid(s));});
test('the second leg interrupts a previously valid route and invalidates the bridge',()=>{const D=engine();let s={...D.initial(),contact:true};s=plan(D,s,['west','bridge','north','drop']);s=D.advance(s).state;const r=D.advance(s);s=r.state;assert.ok(r.event);assert.equal(s.at,'bridge');assert.equal(s.plan.length,0);assert.ok(s.news);assert.ok(D.append(s,'north').error);assert.equal(D.cost(s,D.edge(s,'ring','east')),8);s=walk(D,s,['market','east','drop']);assert.equal(s.stage,'campus');assert.equal(s.at,'drop');assert.ok(s.arrival);assert.ok(D.valid(s));});
test('campus has a covered route, a shorter exposed route, and forbids stairs for trolley',()=>{const D=engine();let s={...D.initial(),stage:'campus',at:'drop',contact:true,arrival:true,news:true};assert.ok(D.append(s,'a').error);let roof=walk(D,s,['canopy','b','desk']);let rain=walk(D,s,['court','hall','desk']);assert.equal(roof.rain,0);assert.equal(rain.rain,4);assert.equal(roof.minutes,7);assert.equal(rain.minutes,6);assert.ok(D.append(roof,'lift').error);assert.ok(D.append({...roof,at:'hall',directions:true},'unit').error);roof.directions=true;roof=walk(D,roof,['lift','unit']);assert.equal(roof.stage,'done');assert.ok(D.valid(roof));});
test('both city corridors reach the hospital after the road event; midtrip save is valid',()=>{const D=engine();for(const initial of [['west','market'],['south','ring']]){let s=walk(D,{...D.initial(),contact:true},initial);assert.ok(s.news);assert.ok(D.valid(JSON.parse(JSON.stringify(s))));s=walk(D,s,['east','drop']);assert.equal(s.stage,'campus');}});
test('invalid saves and old route states do not masquerade as completed remaster',()=>{const D=engine();assert.equal(D.valid({route:['home','unit'],contact:true,closed:true}),false);assert.equal(D.valid({...D.initial(),stage:'done',at:'unit'}),false);assert.equal(D.valid({...D.initial(),minutes:NaN}),false);assert.equal(D.valid({...D.initial(),history:[{stage:'city',from:'home',to:'drop',minutes:1}]}),false);});
test('remastered chapter keeps public resources and legacy link migration',()=>{const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'route.html'),'utf8');for(const m of html.matchAll(/(?:href|src)="([^"#]+)"/g)){assert.ok(fs.existsSync(path.join(root,m[1].split('?')[0])),m[1]);}assert.ok(fs.readFileSync(path.join(root,'assets/js/episodes.js'),'utf8').includes("location.replace('route.html')"));});
