const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
function game(id,seed){const nodes=new Map(),groups={},docEvents={},winEvents={},data={},ctx=new Proxy({},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});let raf,now=0;
 function node(id){const handlers={},n={id,open:false,disabled:false,value:'',textContent:'',style:{},dataset:{},clientWidth:960,width:960,height:560,classList:{toggle(){}},addEventListener(k,f){handlers[k]=f;},fire(k,e){handlers[k]?.(e);},setAttribute(k,v){this[k]=v;},getContext:()=>ctx,getBoundingClientRect:()=>({left:0,top:0,width:960,height:560}),setPointerCapture(p){this.pointer=p;},hasPointerCapture(p){return this.pointer===p;},releasePointerCapture(){this.pointer=null;},focus(){},scrollIntoView(){},showModal(){this.open=true;},close(){this.open=false;},querySelector:()=>({append(){}})};
 let html='';Object.defineProperty(n,'innerHTML',{get:()=>html,set(v){html=v;for(const child of groups[id]||[])if(nodes.get(child.id)===child)nodes.delete(child.id);groups[id]=[];for(const m of v.matchAll(/id="([^"]+)"/g)){const x=node(m[1]);nodes.set(x.id,x);groups[id].push(x);}for(const m of v.matchAll(/<button\b([^>]*)>([\s\S]*?)<\/button>/g)){const a=m[1].match(/data-action="([^"]+)"/);if(a){const x=node('action-'+a[1]);x.dataset.action=a[1];x.disabled=/\bdisabled\b/.test(m[1]);x.textContent=m[2].replace(/<[^>]+>/g,'');groups[id].push(x);}}}});return n;}
 for(const id of ['scene','music','pause','guide','restart','dialog','dialog-content','title','eyebrow','description','boundary','instructions','objective','saved','tools','scene-controls','chapter-status','clock','speech','feedback','journal'])nodes.set(id,node(id));
 class Music{setEnabled(v){this.enabled=v;}setPlaying(v){this.playing=v;}}
 const env={window:{addEventListener:(k,f)=>winEvents[k]=f},document:{hidden:false,getElementById:id=>nodes.get(id)||null,querySelector:()=>node('game'),querySelectorAll:()=>Object.values(groups).flat().filter(n=>n.dataset.action),createElement:()=>node('new'),addEventListener:(k,f)=>docEvents[k]=f},NightMusic:Music,URLSearchParams,location:{search:'?chapter='+id,replace(){}},performance:{now:()=>now},requestAnimationFrame:f=>raf=f,devicePixelRatio:1,localStorage:{getItem:k=>data[k]||null,setItem:(k,v)=>data[k]=v}};
 for(const f of ['series-data.js','series-core.js','recovery-core.js','recovery-scene.js'])vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../assets/js',f),'utf8'),env);
 data['dad-series-v1']=JSON.stringify({complete:{pack:true},sessions:{pack:{preserved:true}}});if(seed)data['dad-recovery-v2-'+id]=JSON.stringify(seed(env.window.RecoveryGames));
 const code=fs.readFileSync(path.join(__dirname,'../assets/js/recovery.js'),'utf8').replace('render();if(s.complete)finish();else show','globalThis.inspect=()=>({s,paused,music,drag});render();if(s.complete)finish();else show');vm.runInNewContext(code,env);
 return {env,nodes,data,inspect:env.inspect,start(){nodes.get('resume').onclick();return this;},action(a){const b=Object.values(groups).flat().find(n=>n.dataset.action===a);assert.ok(b,'missing action '+a);assert.equal(b.disabled,false,'disabled action '+a);b.onclick();return this;},tick(sec){for(let i=0;i<sec*20;i++){now+=50;raf(now);}return this;},events:docEvents};
}
test('new music starts from entry, pause and background freeze simulation, manual mute survives continuation',()=>{
 const g=game('shifts');assert.equal(g.inspect().paused,true);g.start();assert.equal(g.inspect().music.playing,true);g.action('job:review').action('assign').tick(2);const time=g.inspect().s.time;g.nodes.get('pause').onclick();g.tick(5);assert.equal(g.inspect().s.time,time);assert.equal(g.inspect().music.playing,false);g.nodes.get('resume').onclick();g.nodes.get('music').onclick();g.env.document.hidden=true;g.events.visibilitychange();assert.equal(g.inspect().paused,true);g.env.document.hidden=false;g.nodes.get('resume').onclick();assert.equal(g.inspect().music.playing,false);assert.ok(JSON.parse(g.data['dad-series-v1']).sessions.pack.preserved);
});
test('crying UI can finish through accessible alternatives and remains resumable mid-pause',()=>{
 const g=game('soothe').start();for(const k of ['needs','comfort','support'])g.action('observe:'+k);g.nodes.get('light').oninput({target:{value:'35'}});for(const k of ['tv','phone','speaker'])g.action('source:'+k).action('quiet');g.action('environment').action('bed').tick(3).action('place').action('steady-toggle').tick(2);g.nodes.get('pause').onclick();assert.equal(g.inspect().s.holding,false);g.nodes.get('resume').onclick();g.action('steady-toggle').action('help').tick(15).action('handoff');assert.equal(g.inspect().s.complete,true);assert.match(g.nodes.get('dialog-content').innerHTML,/href="recovery.html\?chapter=visitors"/);assert.match(g.nodes.get('dialog-content').innerHTML,/href="series.html"/);assert.equal(g.inspect().music.playing,false);
});
test('call UI does not require reading facts first and click-to-transmit actually sends each fact',()=>{
 const g=game('signal').start();g.action('call');assert.equal(g.inspect().s.called,true);assert.equal(g.inspect().s.observed.length,0);for(const k of ['stage','symptom','since','address'])g.action('observe:'+k).action('speak-click:'+k).tick(3.5);assert.equal(g.inspect().s.sent.length,4);assert.ok(g.nodes.get('scene-controls').innerHTML.includes('data-action="dispatch"'));g.nodes.get('pause').onclick();assert.equal(g.inspect().s.speaking,null);
});
test('visitor click-to-intercom stops after listening and selecting another visitor does not auto-listen',()=>{
 const g=game('visitors').start().tick(15);g.action('person:parcel').action('talk-toggle').tick(3.5);assert.equal(g.inspect().s.talk,3);assert.equal(g.inspect().s.holding,false);g.action('tray').action('person:relative').tick(5);assert.equal(g.inspect().s.talk,0);assert.ok(g.nodes.get('tools').innerHTML.includes('appointment')===false);g.action('talk-toggle').tick(3.5);assert.ok(g.nodes.get('appointment'));
});
