const {test}=require('node:test');
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
function setup(seed={},fail=false){const data={...seed};const env={window:{},localStorage:{getItem:k=>data[k]??null,setItem:(k,v)=>{if(fail)throw Error('blocked');data[k]=v;}}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../assets/js/series-core.js'),'utf8'),env);return {C:env.window.DadSeries,data};}
test('packing rejects overlap and overflow; six-piece solution requires rotation',()=>{const {C}=setup();let a=[];for(const[id,x,y,r] of [['clothes',0,0,false],['supplies',3,0,false],['wash',0,2,false],['baby',2,2,false],['papers',4,2,false]]){a=C.placePack(a,id,x,y,r);assert.ok(a);}assert.equal(C.placePack(a,'charger',4,3,false),null);assert.equal(C.placePack(a,'charger',0,0,true),null);a=C.placePack(a,'charger',4,3,true);assert.equal(a.length,6);assert.ok(C.valid('pack',{placed:a,selected:'charger',rot:true}));});
test('road closure blocks the direct route, a detour remains connected',()=>{const {C}=setup();let route=['home'];route=C.routeMove(route,'a',false);assert.equal(C.routeMove(route,'c',true),null);assert.equal(C.routeMove(route,'unit',true),null);for(const n of ['home','b','d','gate','unit']){route=C.routeMove(route,n,true);assert.ok(route);}assert.equal(route.at(-1),'unit');});
test('adult schedule enforces availability, assignment and simultaneous rest cover',()=>{const {C}=setup();assert.equal(C.assignShift({},'cover',1,0),null);assert.equal(C.assignShift({},'call',0,1),null);let a={};for(const[id,r,t]of [['call',0,0],['shop',0,1],['rest',0,2],['cover',1,2],['meal',0,3],['laundry',1,3]]){a=C.assignShift(a,id,r,t);assert.ok(a);}assert.ok(C.shiftsSolved(a));assert.equal(C.assignShift(a,'laundry',0,0),null);assert.equal(C.shiftsSolved({...a,cover:{row:1,time:3}}),false);});
test('support allocation respects specialties and capacity',()=>{const {C}=setup();assert.equal(C.linkNeed({},'recovery','dad'),null);let a=C.linkNeed({},'food','friend');assert.equal(C.linkNeed(a,'shopping','friend'),null);for(const[n,p]of [['shopping','family'],['calls','dad'],['company','family'],['recovery','clinic'],['feeding','clinic'],['mood','counsel']]){a=C.linkNeed(a,n,p);assert.ok(a);}assert.equal(Object.keys(a).length,7);});
test('all eight sessions survive save/reload, malformed saves recover, old badges integrate',()=>{const {C,data}=setup();for(const id of ['pack','route','handover','shifts','soothe','visitors','signal','network']){const s=C.initial(id);assert.ok(C.valid(id,s),id);C.save(id,s);assert.equal(JSON.stringify(C.load(id)),JSON.stringify(s));C.complete(id);assert.ok(C.finished(id));}const reloaded=setup(data).C;assert.ok(reloaded.finished('network'));assert.equal(setup({'dad-night-best':'8'}).C.finished('night'),true);assert.equal(setup({'dad-series-v1':'{broken'}).C.load('pack').placed.length,0);assert.equal(C.valid('pack',{placed:[{id:'bad'}]}),false);const blocked=setup({},true).C;blocked.save('route',blocked.initial('route'));assert.equal(blocked.storageOK(),false);});
test('public map contains ten distinct chapters and all new episode resources exist',()=>{const root=path.resolve(__dirname,'..');for(const f of ['series.html','adventure.html']){const html=fs.readFileSync(path.join(root,f),'utf8');for(const m of html.matchAll(/(?:src|href)="([^"#]+)"/g)){if(!m[1].startsWith('http'))assert.ok(fs.existsSync(path.join(root,m[1].split('?')[0])),m[1]);}}const env={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'assets/js/series-data.js'),'utf8'),env);assert.equal(new Set(env.window.DAD_CHAPTERS.map(c=>c.id)).size,10);});
