const{test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
function setup(seed){const nodes=new Map(),win={},doc={},store={},groups={};let now=0,raf;const ctx=new Proxy({},{get:()=>()=>{},set:()=>true});
function node(id){const handlers={},n={id,dataset:{},clientWidth:960,width:960,height:560,open:false,hidden:false,textContent:'',disabled:false,closest:()=>null,getContext:()=>ctx,focus(){},scrollIntoView(){},setAttribute(k,v){this[k]=v;},addEventListener(k,f){handlers[k]=f;},fire(k,e){handlers[k]?.(e);},setPointerCapture(){},showModal(){this.open=true;},close(){this.open=false;},querySelectorAll(){return groups[id]||[];}};let html='';Object.defineProperty(n,'innerHTML',{get:()=>html,set(v){html=v;for(const b of groups[id]||[])if(nodes.get(b.id)===b)nodes.delete(b.id);groups[id]=[];for(const m of v.matchAll(/id="([^"]+)"/g)){const x=node(m[1]);nodes.set(x.id,x);}for(const m of v.matchAll(/data-go="([^"]+)"/g)){const b=node('go-'+m[1]);b.dataset.go=m[1];groups[id].push(b);}}});return n;}
for(const id of['scene','music','pause','guide','restart','dialog','dialog-content','nearby','interact','panel','speech','clock','saved','objective','instructions','tools','journal','chapter-status'])nodes.set(id,node(id));const dpad=['up','down','left','right'].map(d=>{const n=node('dir-'+d);n.dataset.dir=d;return n;});class Music{setEnabled(v){this.enabled=v;}setPlaying(v){this.playing=v;}}
const env={window:{addEventListener:(k,f)=>win[k]=f},document:{hidden:false,getElementById:k=>nodes.get(k),querySelectorAll:()=>dpad,addEventListener:(k,f)=>doc[k]=f},NightMusic:Music,devicePixelRatio:1,performance:{now:()=>now},requestAnimationFrame:f=>raf=f,localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v}};
for(const f of['series-data.js','series-core.js','shifts-core.js','shifts-scene.js'])vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../assets/js',f),'utf8'),env);store['dad-series-v1']=JSON.stringify({complete:{night:true},sessions:{pack:{keep:true}}});if(seed)store['dad-shift-room-v1']=JSON.stringify(seed(env.window.DadShift));const code=fs.readFileSync(path.join(__dirname,'../assets/js/shifts.js'),'utf8').replace('render();if(s.complete)finish();else show','globalThis.inspect=()=>({s,paused,keys,music});render();if(s.complete)finish();else show');vm.runInNewContext(code,env);
return{env,nodes,dpad,store,inspect:env.inspect,start(){nodes.get('resume').onclick();return this;},key(k,up=false,repeat=false){win[up?'keyup':'keydown']({key:k,code:k===' '?'Space':k,target:nodes.get('scene'),repeat,preventDefault(){}});return this;},tick(sec){for(let i=0;i<sec*20;i++){now+=50;raf(now);}return this;},win,doc};}
test('WASD and arrow keys actually move; releasing, blur and pause clear held input; mute remains off on resume',()=>{
 const g=setup().start(),x=g.inspect().s.player.x;g.key('d').tick(.3).key('d',true);assert.ok(g.inspect().s.player.x>x+40);const p=g.inspect().s.player.x;g.tick(.3);assert.equal(g.inspect().s.player.x,p);g.key('ArrowLeft').tick(.2);g.win.blur();assert.equal(g.inspect().keys.size,0);g.nodes.get('music').onclick();g.key('w').tick(.1);g.nodes.get('pause').onclick();const t=g.inspect().s.time,pos=JSON.stringify(g.inspect().s.player);g.tick(3);assert.equal(g.inspect().s.time,t);assert.equal(JSON.stringify(g.inspect().s.player),pos);assert.equal(g.inspect().keys.size,0);g.start();assert.equal(g.inspect().music.playing,false);assert.ok(JSON.parse(g.store['dad-series-v1']).sessions.pack.keep);
});
test('E and Space read nearby records, repeated E cannot skip them and movement is blocked while reading',()=>{
 const g=setup(G=>({...G.initial(),player:{x:440,y:245,face:1,step:0}})).start();g.key('e');assert.equal(g.inspect().s.panel,'notes');const p=JSON.stringify(g.inspect().s.player);g.key('e',false,true);assert.equal(g.inspect().s.page,0);g.key('d').tick(.2);assert.equal(JSON.stringify(g.inspect().s.player),p);g.key(' ').key('e').key(' ');assert.equal(g.inspect().s.review,true);assert.equal(g.inspect().s.panel,null);g.key('Escape');assert.equal(g.inspect().paused,true);
});
test('calendar arrow keys change the selected time without walking, touch cancellation releases movement and background freezes',()=>{
 const g=setup(G=>({...G.initial(),review:true,player:{x:780,y:265,face:1,step:0}})).start();g.key('e').key('ArrowLeft');assert.equal(g.inspect().s.slot,0);const p=JSON.stringify(g.inspect().s.player);g.key('e');assert.equal(g.inspect().s.followup,false);g.key('ArrowRight').key('e');assert.equal(g.inspect().s.followup,true);assert.equal(JSON.stringify(g.inspect().s.player),p);const b=g.dpad.find(n=>n.dataset.dir==='down');b.onpointerdown({pointerId:1,preventDefault(){}});g.tick(.2);b.fire('pointercancel',{});assert.equal(g.inspect().keys.size,0);g.env.document.hidden=true;g.doc.visibilitychange();const t=g.inspect().s.time;g.tick(4);assert.equal(g.inspect().s.time,t);assert.equal(g.inspect().paused,true);
});
test('finishing return records awards chapter once and provides next chapter and map exits',()=>{
 const g=setup(G=>({...G.initial(),review:true,followup:true,delivery:true,arrived:true,briefing:3,covered:true,rest:14,player:{x:440,y:245,face:1,step:0}})).start();g.key('e').key('e').key(' ');assert.equal(g.inspect().s.complete,true);assert.equal(g.inspect().paused,true);assert.match(g.nodes.get('dialog-content').innerHTML,/href="recovery.html\?chapter=soothe"/);assert.match(g.nodes.get('dialog-content').innerHTML,/href="series.html"/);assert.equal(JSON.parse(g.store['dad-series-v1']).complete.shifts,true);assert.equal(g.inspect().music.playing,false);
});

test('Escape dismissal of a pause or restart prompt resumes without resetting or leaving an invisible pause',()=>{
 const g=setup().start().key('d').tick(.2).key('d',true);const x=g.inspect().s.player.x;g.nodes.get('restart').onclick();assert.equal(g.inspect().paused,true);let prevented=false;g.nodes.get('dialog').fire('cancel',{preventDefault(){prevented=true;}});assert.equal(prevented,true);assert.equal(g.inspect().paused,false);assert.equal(g.nodes.get('dialog').open,false);assert.equal(g.inspect().s.player.x,x);g.key('d').tick(.2).key('d',true);assert.ok(g.inspect().s.player.x>x);
});
