const{test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
function setup(seed){const nodes=new Map(),win={},doc={},store={},groups={};let now=0,raf;const ctx=new Proxy({},{get:()=>()=>{},set:()=>true});
function node(id){const handlers={},n={id,dataset:{},clientWidth:960,width:960,height:560,open:false,hidden:false,textContent:'',disabled:false,closest:()=>null,getContext:()=>ctx,focus(){},scrollIntoView(){},setAttribute(k,v){this[k]=v;},addEventListener(k,f){handlers[k]=f;},fire(k,e){handlers[k]?.(e);},setPointerCapture(){},showModal(){this.open=true;},close(){this.open=false;},querySelectorAll(){return groups[id]||[];}};let html='';Object.defineProperty(n,'innerHTML',{get:()=>html,set(v){html=v;for(const b of groups[id]||[])if(nodes.get(b.id)===b)nodes.delete(b.id);groups[id]=[];for(const m of v.matchAll(/id="([^"]+)"/g)){const x=node(m[1]);nodes.set(x.id,x);}for(const m of v.matchAll(/data-go="([^"]+)"/g)){const b=node('go-'+m[1]);b.dataset.go=m[1];groups[id].push(b);}}});return n;}
for(const id of['scene','music','pause','guide','restart','dialog','dialog-content','nearby','interact','panel','speech','clock','saved','objective','instructions','tools','journal','chapter-status','call','call-status','call-detail'])nodes.set(id,node(id));const dpad=['up','down','left','right'].map(d=>{const n=node('dir-'+d);n.dataset.dir=d;return n;});class Music{setEnabled(v){this.enabled=v;}setPlaying(v){this.playing=v;}}
const env={window:{addEventListener:(k,f)=>win[k]=f},document:{hidden:false,getElementById:k=>nodes.get(k),querySelectorAll:()=>dpad,addEventListener:(k,f)=>doc[k]=f},NightMusic:Music,devicePixelRatio:1,performance:{now:()=>now},requestAnimationFrame:f=>raf=f,localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v}};
for(const f of['series-data.js','series-core.js','signal-core.js','signal-scene.js'])vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../assets/js',f),'utf8'),env);store['dad-series-v1']=JSON.stringify({complete:{night:true},sessions:{pack:{keep:true}}});if(seed)store['dad-signal-room-v1']=JSON.stringify(seed(env.window.DadSignal));const code=fs.readFileSync(path.join(__dirname,'../assets/js/signal.js'),'utf8').replace('render();if(s.complete)finish();else show','globalThis.inspect=()=>({s,paused,keys,music});render();if(s.complete)finish();else show');vm.runInNewContext(code,env);
return{env,nodes,dpad,store,inspect:env.inspect,start(){nodes.get('resume').onclick();return this;},key(k,up=false,repeat=false){win[up?'keyup':'keydown']({key:k,code:k===' '?'Space':k,target:nodes.get('scene'),repeat,preventDefault(){}});return this;},tick(sec){for(let i=0;i<sec*20;i++){now+=50;raf(now);}return this;},win,doc};}
test('C calls immediately, WASD and touch move, pause freezes all actors and respects manual mute',()=>{
const g=setup().start();assert.equal(g.inspect().music.playing,true);g.key('c');assert.equal(g.inspect().s.called,true);g.key('d').tick(.3).key('d',true);assert.ok(g.inspect().s.player.x>380);const b=g.dpad.find(n=>n.dataset.dir==='down');b.onpointerdown({pointerId:1,preventDefault(){}});g.tick(.2);b.fire('pointercancel',{});assert.equal(g.inspect().keys.size,0);g.nodes.get('music').onclick();g.nodes.get('pause').onclick();const t=g.inspect().s.time;g.tick(5);assert.equal(g.inspect().s.time,t);g.start();assert.equal(g.inspect().music.playing,false);g.env.document.hidden=true;g.doc.visibilitychange();assert.equal(g.inspect().paused,true);
});
test('full UI flow completes with scene movement, updated call status, next/map exits and preserved badges',()=>{
const g=setup().start();g.nodes.get('call').onclick();
function use(id){const b=g.nodes.get('tools').querySelectorAll().find(n=>n.dataset.go===id);assert.ok(b,'destination '+id);b.onclick();g.tick(10);assert.equal(g.nodes.get('interact').disabled,false,id+' in range');g.key('e');}
use('mom');use('charger');use('power');use('intercom');use('cart');assert.equal(g.inspect().s.pushing,true);g.nodes.get('park').onclick();g.tick(4);assert.ok(g.inspect().s.clear);use('mom');assert.match(g.nodes.get('call-detail').textContent,/新变化已更新/);use('door');use('cot');use('records');use('door');g.key('e');use('mom');assert.equal(g.inspect().s.complete,true);assert.match(g.nodes.get('dialog-content').innerHTML,/href="recovery.html\?chapter=network"/);assert.match(g.nodes.get('dialog-content').innerHTML,/href="series.html"/);assert.match(g.nodes.get('dialog-content').innerHTML,/我还在/);const saved=JSON.parse(g.store['dad-series-v1']);assert.equal(saved.complete.signal,true);assert.equal(saved.complete.night,true);assert.ok(saved.sessions.pack.keep);assert.equal(g.inspect().music.playing,false);
});
test('old carry save shows a return destination, E drops the bag and clears the blockage',()=>{const g=setup(G=>({...G.initial(),called:true,brief:true,carry:'records',player:{x:850,y:290,face:1,step:0}})).start();assert.match(g.nodes.get('tools').innerHTML,/走回资料台 · 放回/);const b=g.nodes.get('tools').querySelectorAll().find(n=>n.dataset.go==='records');b.onclick();g.tick(10);assert.equal(g.nodes.get('nearby').textContent,'E · 放回资料袋');g.key('e');assert.equal(g.inspect().s.carry,null);assert.match(g.nodes.get('tools').innerHTML,/走向资料袋/);g.key('e');assert.equal(g.inspect().s.carry,'records');assert.match(g.nodes.get('tools').innerHTML,/走回资料台 · 放回/);});
