const{test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');const env={window:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../assets/js/signal-core.js'),'utf8'),env);const G=env.window.DadSignal;
function tick(s,secs,input){for(let i=0;i<secs*20;i++)s=G.tick(s,.05,input);return s;}
function go(s,id){const p=G.places(s).find(p=>p.id===id);s=G.act(s,'target',p);s=tick(s,15);assert.ok(Math.hypot(s.player.x-p.x,s.player.y-p.y)<=60,id+' reachable '+JSON.stringify(s.player));return s;}
function use(s,id){s=go(s,id);return G.act(s,'interact');}
function prep(){let s=G.act(G.initial(),'call');s=use(s,'mom');s=use(s,'charger');s=use(s,'power');s=use(s,'intercom');s=use(s,'cart');assert.ok(s.pushing);s=G.act(s,'park');s=tick(s,5);assert.ok(s.clear);s=use(s,'door');return s;}
test('call is available from the initial state and remote errands cannot replace proximity',()=>{let s=G.initial();s=G.act(s,'interact');assert.equal(s.brief,false);assert.equal(s.called,false);s=G.act(s,'call');assert.equal(s.called,true);assert.equal(s.events[0],'call');assert.equal(s.carry,null);s=G.act(s,'target',{x:900,y:500});s=tick(s,8);s=G.act(s,'interact');assert.equal(s.brief,false);});
test('real routes, physical cart parking, updated description, bag and return complete the scene',()=>{let s=prep();assert.ok(s.changed);s=use(s,'mom');assert.ok(s.updated);s=use(s,'cot');assert.ok(s.covered);s=use(s,'records');assert.equal(s.carry,'records');s=use(s,'door');assert.ok(s.bag);assert.equal(s.complete,false);s=G.act(s,'interact');assert.ok(s.handoff);assert.equal(s.complete,false);s=use(s,'mom');assert.ok(s.complete);assert.ok(G.valid(s));assert.equal(s.events.filter(e=>e==='brief').length,1);});
test('cart can be pushed by keyboard, released and resumed without losing its position',()=>{let s=G.act(G.initial(),'call');s=use(s,'cart');const start=s.cart.y;s=tick(s,.4,{x:0,y:1});assert.ok(s.cart.y>start+30);s=G.act(s,'interact');const position={...s.cart};assert.equal(s.pushing,false);s=G.restore(s);assert.equal(s.cart.y,position.y);s=G.act(s,'interact');assert.ok(s.pushing);s=tick(s,1,{x:0,y:1});s=tick(s,.8,{x:1,y:0});s=tick(s,.2,{x:-1,y:0});s=tick(s,.2,{x:0,y:-1});assert.ok(s.clear);assert.ok(Math.hypot(s.cart.x-885,s.cart.y-485)<28);});
test('missing update and missing care handoff prevent final handoff without a health failure',()=>{let s=prep();s=use(s,'records');s=use(s,'door');assert.ok(s.bag);s=G.act(s,'interact');assert.equal(s.handoff,false);assert.match(s.message,/新/);s=use(s,'mom');s=use(s,'door');assert.equal(s.handoff,false);assert.match(s.message,/照护/);s=tick(s,100);assert.equal(s.complete,false);s=use(s,'cot');s=use(s,'door');assert.ok(s.handoff);});
test('scene tasks can be completed in a different order and helper reaches bedside',()=>{let s=G.act(G.initial(),'call');s=use(s,'mom');s=use(s,'intercom');s=use(s,'door');s=use(s,'cot');assert.equal(s.covered,true);s=use(s,'cart');s=G.act(s,'park');s=tick(s,4);s=use(s,'mom');s=use(s,'charger');s=use(s,'power');s=use(s,'records');s=use(s,'door');s=G.act(s,'interact');s=use(s,'mom');assert.ok(s.complete);});
test('restore rejects corrupt positions and impossible completed saves, stops movement and keeps errands',()=>{const s=prep();const reloaded=G.restore(s);assert.equal(reloaded.path.length,0);assert.equal(reloaded.pushing,false);assert.equal(reloaded.clear,true);assert.equal(reloaded.called,true);assert.ok(G.valid(reloaded));assert.equal(G.restore({...s,complete:true}).called,false);assert.equal(G.restore({...s,player:{x:100,y:220}}).called,false);});
test('new and old entries have navigation and valid assets, legacy entry still exists',()=>{const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'signal.html'),'utf8');for(const m of html.matchAll(/(?:src|href)="([^"#]+)"/g))if(!m[1].startsWith('http'))assert.ok(fs.existsSync(path.join(root,m[1].split('?')[0])),m[1]);assert.match(fs.readFileSync(path.join(root,'assets/js/recovery.js'),'utf8'),/id==='signal'.*location.replace\('signal.html'\)/);});
test('early bag pickup can be put back, cart parked, then retrieved and handed over',()=>{let s=G.act(G.initial(),'call');s=use(s,'mom');s=use(s,'records');assert.equal(s.carry,'records');s=use(s,'cart');assert.equal(s.pushing,false);s=use(s,'records');assert.equal(s.carry,null);assert.ok(G.valid(G.restore(s)));s=use(s,'cart');assert.ok(s.pushing);s=G.act(s,'park');s=tick(s,5);assert.ok(s.clear);s=use(s,'mom');s=use(s,'charger');s=use(s,'power');s=use(s,'intercom');s=use(s,'cot');s=use(s,'records');s=use(s,'door');s=tick(s,3);s=G.act(s,'interact');assert.ok(s.bag);s=G.act(s,'interact');s=use(s,'mom');assert.ok(s.complete);});
test('charger can also be put back and picked up again without losing the call',()=>{let s=G.act(G.initial(),'call');s=use(s,'charger');assert.equal(s.carry,'charger');s=G.act(s,'interact');assert.equal(s.carry,null);s=G.act(s,'interact');assert.equal(s.carry,'charger');assert.equal(s.called,true);s=use(s,'power');assert.equal(s.charging,true);});
test('item labels are drawn where the item is, removed at origin when carried or handed over',()=>{const labels=[],ctx=new Proxy({fillText:(text,x,y)=>labels.push({text,x,y})},{get:(o,k)=>o[k]||(()=>{}),set:(o,k,v)=>(o[k]=v,true)});const e={window:{},devicePixelRatio:1};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../assets/js/signal-scene.js'),'utf8'),e);const canvas={clientWidth:960,width:960,height:560,getContext:()=>ctx};function draw(s){labels.length=0;e.window.DadSignalScene.draw(canvas,s);return labels.filter(t=>t.text==='资料袋'||t.text==='充电线');}const s=G.initial();assert.ok(draw(s).some(t=>t.text==='资料袋'&&t.x===577));const carried=draw({...s,carry:'records'});assert.equal(carried.filter(t=>t.text==='资料袋').length,1);assert.equal(carried.find(t=>t.text==='资料袋').x,s.player.x+43);assert.equal(draw({...s,bag:true,charging:true}).length,0);assert.ok(draw({...s,carry:null}).some(t=>t.text==='资料袋'&&t.x===577));});
