const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');const root=path.join(__dirname,'..'),ctx={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'assets/js/visitors-core.js'),'utf8'),ctx);const G=ctx.window.DadVisitors;
function walk(s,id){const p=id==='guest'?s.guest:G.stationsFor(s).find(p=>p.id===id);s=G.act(s,'target',p);for(let i=0;i<900&&s.path.length;i++)s=G.tick(s,.1);assert.ok(G.nearest(s).d<68,'can reach '+id);return s;}
function touch(s,id){s=walk(s,id);if(id==='guest')assert.equal(G.nearest(s).id,'guest');s=G.act(s,'interact');return s;}
function choose(s,a){assert.ok(G.dialogue(s).options.some(x=>x[0]===a));return G.act(s,'choose',a);}
function setup(){let s=G.initial();s=choose(touch(s,'mom'),'consent');s=choose(touch(s,'intercom'),'parcelKnown');s=touch(s,'door');s=touch(s,'kitchen');s=choose(touch(s,'intercom'),'grandmaKnown');s=touch(s,'curtain');s=touch(s,'door');return s;}
function lead(s,points){for(const p of points){s=G.act(s,'target',p);for(let i=0;i<400&&s.path.length;i++)s=G.tick(s,.1);for(let i=0;i<15;i++)s=G.tick(s,.1);}return s;}
function seat(s){s=lead(s,[{x:820,y:305},{x:780,y:305},{x:720,y:305},{x:680,y:305}]);s=touch(s,'sofa');assert.equal(s.seated,true);return s;}
function nearGuest(s){s=G.act(s,'target',{x:s.guest.x,y:s.guest.y+45});for(let i=0;i<900&&s.path.length;i++)s=G.tick(s,.1);assert.equal(G.nearest(s).id,'guest');return G.act(s,'interact');}
function full(friend,photo,followup){let s=seat(setup());s=choose(touch(s,'intercom'),friend);s=choose(touch(s,'mom'),photo);s=nearGuest(s);assert.equal(s.fatigue,true);s=choose(nearGuest(s),'leave');s=lead(s,[{x:760,y:345},{x:820,y:345},{x:875,y:365}]);s=touch(s,'door');assert.equal(s.departed,true);s=touch(s,'door');s=touch(s,'mom');s=choose(touch(s,'phone'),followup);return s;}
test('both consent-respecting branches complete a real room journey and survive restore',()=>{for(const combo of[['friend-gift','photo-private','followup-visit'],['friend-call','photo-no','followup-meal']]){const s=full(...combo);assert.equal(s.complete,true);assert.equal(G.valid(s),true);assert.equal(G.restore(s).complete,true);assert.ok(s.player.step>1500);assert.ok(s.events.includes('change-plan'));}});
test('cannot accept visit remotely or before maternal agreement, identity and privacy',()=>{let s=G.initial();const out=G.act(s,'interact');assert.equal(out.consent,false);s=touch(s,'door');assert.equal(s.guest,null);assert.equal(s.carried,false);s=choose(touch(s,'mom'),'consent');s=choose(touch(s,'intercom'),'parcelKnown');s=touch(s,'door');assert.equal(s.carried,true);s=touch(s,'kitchen');s=touch(s,'door');assert.equal(s.guest,null);s=choose(touch(s,'intercom'),'grandmaKnown');s=touch(s,'door');assert.equal(s.guest,null);assert.match(s.message,/隐私/);});
test('follower waits when dad runs off and cannot enter bedroom; no visit expiry',()=>{let s=setup();const start={...s.guest};s.player={...s.player,x:370,y:365};for(let i=0;i<200;i++)s=G.tick(s,.1);assert.equal(s.guest.x,start.x);assert.equal(s.guest.y,start.y);assert.equal(s.departed,false);s.player={...s.player,x:870,y:415};for(let i=0;i<70;i++)s=G.tick(s,.1);assert.ok(s.guest.y>start.y);assert.ok(s.guest.x>=520);});
test('manual motion respects furniture and diagonal speed; carrying slows down',()=>{let s=G.initial();s.player={x:400,y:470,face:1,step:0};const a=G.tick(s,.1,{x:-1,y:0}),b=G.tick(s,.1,{x:-1,y:-1});assert.ok(Math.abs(Math.hypot(b.player.x-400,b.player.y-470)-16.5)<.01);s.carried=true;assert.ok(Math.abs(G.tick(s,.1,{x:-1,y:0}).player.x-400)<Math.abs(a.player.x-400));s=G.initial();s.player={x:445,y:250,face:1,step:0};for(let i=0;i<100;i++)s=G.tick(s,.1,{x:1,y:0});assert.ok(s.player.x<=456);assert.ok(G.walkable(s.player.x,s.player.y));});
test('photography cannot proceed on behalf of mom; photo permission does not imply sharing',()=>{let s=seat(setup());s=choose(touch(s,'intercom'),'friend-call');s=nearGuest(s);assert.equal(s.photoDone,false);s=choose(touch(s,'mom'),'photo-private');assert.equal(s.photo,'private');s=nearGuest(s);assert.equal(s.photoDone,true);assert.match(s.message,/不转发/);});
test('leaving and closed door alone do not complete chapter: check current needs and future plan',()=>{let s=full('friend-call','photo-no','followup-meal');s.complete=false;s.followup=null;s.checked=false;assert.equal(G.act(s,'interact').complete,false);assert.equal(G.act(s,'choose','followup-meal').complete,false);});
test('corrupt save rejected and restore clears unfinished input without removing story',()=>{let s=setup();s.path=[{x:825,y:385}];s.panel='grandma';const n=G.restore(s);assert.equal(n.guest.mode,'follow');assert.equal(n.path.length,0);assert.equal(n.panel,null);s.player.x=480;s.player.y=250;assert.equal(G.restore(s).consent,false);s=G.initial();s.choice=1;s.panel='consent';assert.equal(G.valid(s),false);});

test('one destination click can lead the visitor to the sofa without deadlock',()=>{let s=setup();s=walk(s,'sofa');for(let i=0;i<40;i++)s=G.tick(s,.1);s=G.act(s,'interact');assert.equal(s.seated,true);});

test('seating does not teleport the visitor onto dad even when he stands by a cushion',()=>{for(const x of [655,680,710,720,735]){let s=setup();s.player={x,y:310,face:1,step:0};s.guest={x:750,y:365,face:-1,step:0,mode:'follow'};s=G.act(s,'interact');assert.equal(s.seated,true);assert.ok(Math.hypot(s.player.x-s.guest.x,s.player.y-s.guest.y)>=52);assert.equal(G.valid(s),true);}});

test('restored older seated saves separate overlapping actors without wiping progress',()=>{let s=seat(setup());s.player={...s.player,x:s.guest.x,y:s.guest.y};const n=G.restore(s);assert.equal(n.seated,true);assert.ok(Math.hypot(n.player.x-n.guest.x,n.player.y-n.guest.y)>=52);assert.equal(n.events.length,s.events.length);});
