const{test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
function setup(seed){const nodes=new Map(),win={},doc={},store={},groups={};let now=0,raf;const ctx=new Proxy({},{get:()=>()=>{},set:()=>true});
function node(id){const handlers={},n={id,dataset:{},clientWidth:960,width:960,height:560,open:false,hidden:false,textContent:'',disabled:false,closest:()=>null,getContext:()=>ctx,focus(){},scrollIntoView(){},setAttribute(k,v){this[k]=v;},addEventListener(k,f){handlers[k]=f;},fire(k,e){handlers[k]?.(e);},setPointerCapture(){},showModal(){this.open=true;},close(){this.open=false;},querySelectorAll(){return groups[id]||[];}};let html='';Object.defineProperty(n,'innerHTML',{get:()=>html,set(v){html=v;for(const b of groups[id]||[])if(nodes.get(b.id)===b)nodes.delete(b.id);groups[id]=[];for(const m of v.matchAll(/id="([^"]+)"/g)){const x=node(m[1]);nodes.set(x.id,x);}for(const m of v.matchAll(/data-go="([^"]+)"/g)){const b=node('go-'+m[1]);b.dataset.go=m[1];groups[id].push(b);}}});return n;}
for(const id of['scene','music','pause','guide','restart','dialog','dialog-content','nearby','interact','panel','speech','clock','saved','objective','instructions','tools','journal','chapter-status'])nodes.set(id,node(id));const dpad=['up','down','left','right'].map(d=>{const n=node('dir-'+d);n.dataset.dir=d;return n;});class Music{setEnabled(v){this.enabled=v;}setPlaying(v){this.playing=v;}}
const env={window:{addEventListener:(k,f)=>win[k]=f},document:{hidden:false,getElementById:k=>nodes.get(k),querySelectorAll:()=>dpad,addEventListener:(k,f)=>doc[k]=f},NightMusic:Music,devicePixelRatio:1,performance:{now:()=>now},requestAnimationFrame:f=>raf=f,localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v}};
for(const f of['series-data.js','series-core.js','visitors-core.js','visitors-scene.js'])vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../assets/js',f),'utf8'),env);store['dad-series-v1']=JSON.stringify({complete:{night:true},sessions:{pack:{keep:true}}});if(seed)store['dad-visitors-room-v1']=JSON.stringify(seed(env.window.DadVisitors));const code=fs.readFileSync(path.join(__dirname,'../assets/js/visitors.js'),'utf8').replace('render();if(s.complete)finish();else show','globalThis.inspect=()=>({s,paused,keys,music});render();if(s.complete)finish();else show');vm.runInNewContext(code,env);
return{env,nodes,dpad,store,inspect:env.inspect,start(){nodes.get('resume').onclick();return this;},key(k,up=false,repeat=false){win[up?'keyup':'keydown']({key:k,code:k===' '?'Space':k,target:nodes.get('scene'),repeat,preventDefault(){}});return this;},tick(sec){for(let i=0;i<sec*20;i++){now+=50;raf(now);}return this;},win,doc};}
test('keyboard movement, release and pause work; music defaults on and respects mute',()=>{
const g=setup().start(),x=g.inspect().s.player.x;assert.equal(g.inspect().music.playing,true);g.key('d').tick(.3).key('d',true);assert.ok(g.inspect().s.player.x>x+40);const p=g.inspect().s.player.x;g.tick(.3);assert.equal(g.inspect().s.player.x,p);g.nodes.get('music').onclick();g.key('w');g.nodes.get('pause').onclick();const t=g.inspect().s.time;g.tick(4);assert.equal(g.inspect().s.time,t);assert.equal(g.inspect().keys.size,0);g.start();assert.equal(g.inspect().music.playing,false);
});
test('nearby dialogue uses keyboard selection, freezes walking and ignores repeated confirmations',()=>{
const g=setup(G=>({...G.initial(),consent:true,parcelKnown:true,parcel:true,grandmaKnown:true,curtain:true,friendPending:true,guest:{x:735,y:295,mode:'sit',step:0,face:1},seated:true,player:{x:850,y:290,face:1,step:0}})).start();g.key('e');assert.equal(g.inspect().s.panel,'friend');const x=g.inspect().s.player.x;g.key('d').tick(.2);assert.equal(g.inspect().s.player.x,x);g.key('ArrowDown');assert.equal(g.inspect().s.choice,1);g.key('e',false,true);assert.equal(g.inspect().s.friendPlan,null);g.key(' ');assert.equal(g.inspect().s.friendPlan,'call');assert.equal(g.inspect().keys.size,0);
});
test('touch cancellation and page hiding stop movement; Escape can resume a modal',()=>{
const g=setup().start(),b=g.dpad.find(n=>n.dataset.dir==='down');b.onpointerdown({pointerId:1,preventDefault(){}});g.tick(.2);b.fire('pointercancel',{});assert.equal(g.inspect().keys.size,0);g.env.document.hidden=true;g.doc.visibilitychange();const t=g.inspect().s.time;g.tick(5);assert.equal(g.inspect().s.time,t);g.nodes.get('dialog').fire('cancel',{preventDefault(){}});assert.equal(g.inspect().paused,false);assert.equal(g.nodes.get('dialog').open,false);
});
test('completion preserves existing map badges and provides next and map exits',()=>{
const g=setup(G=>({...G.initial(),consent:true,parcelKnown:true,parcel:true,grandmaKnown:true,curtain:true,seated:true,photo:'no',photoDone:true,friendPlan:'gift',fatigue:true,departed:true,closed:true,checked:true,player:{x:550,y:450,face:1,step:0}})).start();g.key('e').key('ArrowDown').key(' ');assert.equal(g.inspect().s.complete,true);assert.match(g.nodes.get('dialog-content').innerHTML,/href="recovery.html\?chapter=signal"/);assert.match(g.nodes.get('dialog-content').innerHTML,/href="series.html"/);const saved=JSON.parse(g.store['dad-series-v1']);assert.equal(saved.complete.visitors,true);assert.equal(saved.complete.night,true);assert.ok(saved.sessions.pack.keep);assert.equal(g.inspect().music.playing,false);
});
